// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxedhsqvhwaxdbqitxvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4ZWRoc3F2aHdheGRicWl0eHZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTMyNjUsImV4cCI6MjA2MzkyOTI2NX0.wKhY7Y0XoG0_PxcWay2EgkmAfsDybenjTbWTtC_ltco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);